version: '3.4'

services:
  graphwise-reactodia:
    image: node:22-alpine
    working_dir: /app
    user: "${UID}:${GID}"
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: npm run start
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget -q -O - http://graphwise-reactodia:3333/pages/index.html | grep -q 'Graphwise Reactodia'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cypress:
    image: cypress/included:15.17.0
    depends_on:
      graphwise-reactodia:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://graphwise-reactodia:3333
      - NO_COLOR=true
    user: "${UID}:${GID}"
    working_dir: /e2e
    volumes:
      - ./:/e2e
    command: cypress run --browser chrome --config-file cypress.config.js
