/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ReactodiaConfig } from "./components/graphwise-reactodia/models/reactodia-config";
import { LanguageKey } from "./components/graphwise-reactodia/i18n/language-key";
import { SparqlDataProviderSettings } from "@reactodia/workspace";
export { ReactodiaConfig } from "./components/graphwise-reactodia/models/reactodia-config";
export { LanguageKey } from "./components/graphwise-reactodia/i18n/language-key";
export { SparqlDataProviderSettings } from "@reactodia/workspace";
export namespace Components {
    /**
     * A web component that renders a graph with the Reactodia workspace.
     * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
     * the active repository's endpoint via `current-repository` and a `config.queryFunction`
     * that performs the actual HTTP request. Reactodia fetches all node, link and type data
     * lazily through them; the canvas starts empty and the user populates it via the search bar.
     * The component is a thin wrapper around Reactodia: query configuration lives outside the
     * wrapper and is supplied through the `providerSettings` prop.
     */
    interface GraphwiseReactodia {
        /**
          * Host-supplied configuration: the SPARQL `queryFunction` transport and an optional `seed` set of entities to pre-populate the canvas with. A DOM property (an object, not an attribute) passed in from outside the wrapper.  Read once on mount; not watched, as it only sets up the data source and initial canvas.
         */
        "config"?: ReactodiaConfig;
        /**
          * The active repository id. Appended to {@link queryFunction } as the request `url`; changing it re-points the graph at the new repository (and resets the canvas), which is how runtime repository changes are handled.
         */
        "currentRepository"?: string;
        /**
          * UI language code (e.g. `en`, `fr`) for the Reactodia interface. Defaults to English.
          * @default LanguageKey.EN
         */
        "language": LanguageKey;
        /**
          * Query preset for the SPARQL data provider, owned and configured by the host. A DOM property (an object, not an attribute) passed in from outside the wrapper. When omitted, the data provider falls back to Reactodia's generic OWL/RDFS preset. Changing it rebuilds the data provider and resets the canvas.
         */
        "providerSettings"?: SparqlDataProviderSettings;
    }
}
declare global {
    /**
     * A web component that renders a graph with the Reactodia workspace.
     * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
     * the active repository's endpoint via `current-repository` and a `config.queryFunction`
     * that performs the actual HTTP request. Reactodia fetches all node, link and type data
     * lazily through them; the canvas starts empty and the user populates it via the search bar.
     * The component is a thin wrapper around Reactodia: query configuration lives outside the
     * wrapper and is supplied through the `providerSettings` prop.
     */
    interface HTMLGraphwiseReactodiaElement extends Components.GraphwiseReactodia, HTMLStencilElement {
    }
    var HTMLGraphwiseReactodiaElement: {
        prototype: HTMLGraphwiseReactodiaElement;
        new (): HTMLGraphwiseReactodiaElement;
    };
    interface HTMLElementTagNameMap {
        "graphwise-reactodia": HTMLGraphwiseReactodiaElement;
    }
}
declare namespace LocalJSX {
    /**
     * A web component that renders a graph with the Reactodia workspace.
     * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
     * the active repository's endpoint via `current-repository` and a `config.queryFunction`
     * that performs the actual HTTP request. Reactodia fetches all node, link and type data
     * lazily through them; the canvas starts empty and the user populates it via the search bar.
     * The component is a thin wrapper around Reactodia: query configuration lives outside the
     * wrapper and is supplied through the `providerSettings` prop.
     */
    interface GraphwiseReactodia {
        /**
          * Host-supplied configuration: the SPARQL `queryFunction` transport and an optional `seed` set of entities to pre-populate the canvas with. A DOM property (an object, not an attribute) passed in from outside the wrapper.  Read once on mount; not watched, as it only sets up the data source and initial canvas.
         */
        "config"?: ReactodiaConfig;
        /**
          * The active repository id. Appended to {@link queryFunction } as the request `url`; changing it re-points the graph at the new repository (and resets the canvas), which is how runtime repository changes are handled.
         */
        "currentRepository"?: string;
        /**
          * UI language code (e.g. `en`, `fr`) for the Reactodia interface. Defaults to English.
          * @default LanguageKey.EN
         */
        "language"?: LanguageKey;
        /**
          * Query preset for the SPARQL data provider, owned and configured by the host. A DOM property (an object, not an attribute) passed in from outside the wrapper. When omitted, the data provider falls back to Reactodia's generic OWL/RDFS preset. Changing it rebuilds the data provider and resets the canvas.
         */
        "providerSettings"?: SparqlDataProviderSettings;
    }
    interface IntrinsicElements {
        "graphwise-reactodia": GraphwiseReactodia;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A web component that renders a graph with the Reactodia workspace.
             * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
             * the active repository's endpoint via `current-repository` and a `config.queryFunction`
             * that performs the actual HTTP request. Reactodia fetches all node, link and type data
             * lazily through them; the canvas starts empty and the user populates it via the search bar.
             * The component is a thin wrapper around Reactodia: query configuration lives outside the
             * wrapper and is supplied through the `providerSettings` prop.
             */
            "graphwise-reactodia": LocalJSX.GraphwiseReactodia & JSXBase.HTMLAttributes<HTMLGraphwiseReactodiaElement>;
        }
    }
}
