/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SparqlDataProviderSettings, SparqlQueryFunction } from "@reactodia/workspace";
export { SparqlDataProviderSettings, SparqlQueryFunction } from "@reactodia/workspace";
export namespace Components {
    /**
     * A web component that renders a graph with the Reactodia workspace.
     * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
     * the active repository's endpoint via `current-repository` and a `queryFunction` that
     * performs the actual HTTP request. Reactodia fetches all node, link and type data lazily
     * through them; the canvas starts empty and the user populates it via the search bar.
     * The component is a thin wrapper around Reactodia: query configuration lives outside the
     * wrapper and is supplied through the `providerSettings` prop.
     */
    interface GraphwiseReactodia {
        /**
          * The active repository id. Appended to {@link queryFunction} as the request `url`; changing it re-points the graph at the new repository (and resets the canvas), which is how runtime repository changes are handled.
         */
        "currentRepository": string;
        /**
          * UI language code (e.g. `en`, `fr`) for the Reactodia interface. Defaults to English.
          * @default 'en'
         */
        "language": string;
        /**
          * Query preset for the SPARQL data provider, owned and configured by the host. A DOM property (an object, not an attribute) passed in from outside the wrapper. When omitted, the data provider falls back to Reactodia's generic OWL/RDFS preset. Changing it rebuilds the data provider and resets the canvas.
         */
        "providerSettings"?: SparqlDataProviderSettings;
        /**
          * HTTP transport for the SPARQL requests. Set by the host so requests go through the host's HTTP layer (auth, interceptors) instead of a built-in `fetch`.
         */
        "queryFunction": SparqlQueryFunction;
    }
}
declare global {
    /**
     * A web component that renders a graph with the Reactodia workspace.
     * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
     * the active repository's endpoint via `current-repository` and a `queryFunction` that
     * performs the actual HTTP request. Reactodia fetches all node, link and type data lazily
     * through them; the canvas starts empty and the user populates it via the search bar.
     * The component is a thin wrapper around Reactodia: query configuration lives outside the
     * wrapper and is supplied through the `providerSettings` prop.
     */
    interface HTMLGraphwiseReactodiaElement extends Components.GraphwiseReactodia, HTMLStencilElement {
    }
    var HTMLGraphwiseReactodiaElement: {
        prototype: HTMLGraphwiseReactodiaElement;
        new (): HTMLGraphwiseReactodiaElement;
    };
    interface HTMLElementTagNameMap {
        "graphwise-reactodia": HTMLGraphwiseReactodiaElement;
    }
}
declare namespace LocalJSX {
    /**
     * A web component that renders a graph with the Reactodia workspace.
     * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
     * the active repository's endpoint via `current-repository` and a `queryFunction` that
     * performs the actual HTTP request. Reactodia fetches all node, link and type data lazily
     * through them; the canvas starts empty and the user populates it via the search bar.
     * The component is a thin wrapper around Reactodia: query configuration lives outside the
     * wrapper and is supplied through the `providerSettings` prop.
     */
    interface GraphwiseReactodia {
        /**
          * The active repository id. Appended to {@link queryFunction} as the request `url`; changing it re-points the graph at the new repository (and resets the canvas), which is how runtime repository changes are handled.
         */
        "currentRepository"?: string;
        /**
          * UI language code (e.g. `en`, `fr`) for the Reactodia interface. Defaults to English.
          * @default 'en'
         */
        "language"?: string;
        /**
          * Query preset for the SPARQL data provider, owned and configured by the host. A DOM property (an object, not an attribute) passed in from outside the wrapper. When omitted, the data provider falls back to Reactodia's generic OWL/RDFS preset. Changing it rebuilds the data provider and resets the canvas.
         */
        "providerSettings"?: SparqlDataProviderSettings;
        /**
          * HTTP transport for the SPARQL requests. Set by the host so requests go through the host's HTTP layer (auth, interceptors) instead of a built-in `fetch`.
         */
        "queryFunction"?: SparqlQueryFunction;
    }
    interface IntrinsicElements {
        "graphwise-reactodia": GraphwiseReactodia;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A web component that renders a graph with the Reactodia workspace.
             * The component is backed by a SPARQL endpoint but is endpoint-agnostic: the host passes
             * the active repository's endpoint via `current-repository` and a `queryFunction` that
             * performs the actual HTTP request. Reactodia fetches all node, link and type data lazily
             * through them; the canvas starts empty and the user populates it via the search bar.
             * The component is a thin wrapper around Reactodia: query configuration lives outside the
             * wrapper and is supplied through the `providerSettings` prop.
             */
            "graphwise-reactodia": LocalJSX.GraphwiseReactodia & JSXBase.HTMLAttributes<HTMLGraphwiseReactodiaElement>;
        }
    }
}
